# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60bdcb1cf17ffcd08cc67d8fb9979358ed328596adeac5eef18f0564660776d0fcbcea7ac561a0cdbec8df6123e41c595de338981ef85e0e8cc30fcf47f9ab8a

test:
  secret_key_base: e5b5b1c5412673130f1c636ab0720b0364955254729a1f6530ddb134001d8a421f462a0ddfd7ab725b5ed18cb3812890b9ac8e666a60899c9d009cc3993315ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
